-- Generated by scripts/mail-templates-sql.mjs from src/mail-templates.ts.
insert into mail_templates (key, lang, subject, body) values ('thanks', 'nl', 'Je afspraak bij BarberBjorn staat vast', 'Hoi {{name}},

Bedankt voor je boeking. Je afspraak staat vast:

{{service}}
{{date}} om {{time}}
Ferdinandstraat 21, Axel

Lukt het toch niet? Stuur even een mail terug, dan zoeken we een ander moment.

Tot dan,
Bjorn')
  on conflict (key, lang) do update set subject = excluded.subject, body = excluded.body
  where mail_templates.body = 'Hoi {{name}}, je {{service}} staat op {{date}} om {{time}}. Tot dan. Bjorn';
insert into mail_templates (key, lang, subject, body) values ('thanks', 'en', 'Your appointment at BarberBjorn is booked', 'Hi {{name}},

Thanks for booking. Your appointment is set:

{{service}}
{{date}} at {{time}}
Ferdinandstraat 21, Axel

Can''t make it after all? Just reply to this mail and we''ll find another time.

See you then,
Bjorn')
  on conflict (key, lang) do update set subject = excluded.subject, body = excluded.body
  where mail_templates.body = 'Hi {{name}}, your {{service}} is on {{date}} at {{time}}. See you then. Bjorn';
insert into mail_templates (key, lang, subject, body) values ('accepted', 'nl', 'Je afspraak bij BarberBjorn is bevestigd', 'Hoi {{name}},

Goed nieuws: je gevraagde tijd past. Je afspraak staat vast:

{{service}}
{{date}} om {{time}}
Ferdinandstraat 21, Axel

Tot dan,
Bjorn')
  on conflict (key, lang) do update set subject = excluded.subject, body = excluded.body
  where mail_templates.body = 'Hoi {{name}}, je {{service}} op {{date}} om {{time}} is bevestigd. Bjorn';
insert into mail_templates (key, lang, subject, body) values ('accepted', 'en', 'Your appointment at BarberBjorn is confirmed', 'Hi {{name}},

Good news: the time you asked for works. Your appointment is set:

{{service}}
{{date}} at {{time}}
Ferdinandstraat 21, Axel

See you then,
Bjorn')
  on conflict (key, lang) do update set subject = excluded.subject, body = excluded.body
  where mail_templates.body = 'Hi {{name}}, your {{service}} on {{date}} at {{time}} is confirmed. Bjorn';
insert into mail_templates (key, lang, subject, body) values ('declined', 'nl', 'Dat tijdstip lukt helaas niet', 'Hoi {{name}},

{{date}} om {{time}} lukt helaas niet. Kies een vrije tijd op de site, of stuur een mail terug, dan zoeken we samen een ander moment.

Groet,
Bjorn')
  on conflict (key, lang) do update set subject = excluded.subject, body = excluded.body
  where mail_templates.body = 'Hoi {{name}}, {{date}} om {{time}} lukt niet. Mail of bel voor een andere tijd. Bjorn';
insert into mail_templates (key, lang, subject, body) values ('declined', 'en', 'That time doesn''t work, sorry', 'Hi {{name}},

{{date}} at {{time}} doesn''t work, sorry. Pick a free time on the site, or reply to this mail and we''ll find another moment together.

Best,
Bjorn')
  on conflict (key, lang) do update set subject = excluded.subject, body = excluded.body
  where mail_templates.body = 'Hi {{name}}, {{date}} at {{time}} is not possible. Mail or call for another time. Bjorn';
insert into mail_templates (key, lang, subject, body) values ('moved', 'nl', 'Je afspraak bij BarberBjorn is verplaatst', 'Hoi {{name}},

Je afspraak is verplaatst naar een nieuw moment:

{{service}}
{{date}} om {{time}}
Ferdinandstraat 21, Axel

Past dit niet? Stuur even een mail terug, dan zoeken we een ander moment.

Tot dan,
Bjorn')
  on conflict (key, lang) do update set subject = excluded.subject, body = excluded.body
  where false;
insert into mail_templates (key, lang, subject, body) values ('moved', 'en', 'Your appointment at BarberBjorn has moved', 'Hi {{name}},

Your appointment has moved to a new time:

{{service}}
{{date}} at {{time}}
Ferdinandstraat 21, Axel

Doesn''t this work for you? Just reply to this mail and we''ll find another time.

See you then,
Bjorn')
  on conflict (key, lang) do update set subject = excluded.subject, body = excluded.body
  where false;
