-- Generated by scripts/mail-templates-update-sql.mjs from src/mail-templates.ts.
insert into mail_templates (key, lang, subject, body) values ('thanks', 'nl', 'Je afspraak bij Bjorn’s Barber staat vast', 'Hoi {{name}},

Bedankt voor je boeking. Je afspraak staat vast:

{{service}}
{{date}} om {{time}}
Ferdinandstraat 21, Axel

Lukt het toch niet? Stuur even een mail terug, dan zoeken we een ander moment.

Tot dan,
Bjorn')
  on conflict (key, lang) do nothing;
update mail_templates set subject = 'Je afspraak bij Bjorn’s Barber staat vast', body = 'Hoi {{name}},

Bedankt voor je boeking. Je afspraak staat vast:

{{service}}
{{date}} om {{time}}
Ferdinandstraat 21, Axel

Lukt het toch niet? Stuur even een mail terug, dan zoeken we een ander moment.

Tot dan,
Bjorn'
  where key = 'thanks' and lang = 'nl' and subject = 'Je afspraak bij BarberBjorn staat vast' and body = 'Hoi {{name}},

Bedankt voor je boeking. Je afspraak staat vast:

{{service}}
{{date}} om {{time}}
Ferdinandstraat 21, Axel

Lukt het toch niet? Stuur even een mail terug, dan zoeken we een ander moment.

Tot dan,
Bjorn';
insert into mail_templates (key, lang, subject, body) values ('thanks', 'en', 'Your appointment at Bjorn’s Barber is booked', 'Hi {{name}},

Thanks for booking. Your appointment is set:

{{service}}
{{date}} at {{time}}
Ferdinandstraat 21, Axel

Can''t make it after all? Just reply to this mail and we''ll find another time.

See you then,
Bjorn')
  on conflict (key, lang) do nothing;
update mail_templates set subject = 'Your appointment at Bjorn’s Barber is booked', body = 'Hi {{name}},

Thanks for booking. Your appointment is set:

{{service}}
{{date}} at {{time}}
Ferdinandstraat 21, Axel

Can''t make it after all? Just reply to this mail and we''ll find another time.

See you then,
Bjorn'
  where key = 'thanks' and lang = 'en' and subject = 'Your appointment at BarberBjorn is booked' and body = 'Hi {{name}},

Thanks for booking. Your appointment is set:

{{service}}
{{date}} at {{time}}
Ferdinandstraat 21, Axel

Can''t make it after all? Just reply to this mail and we''ll find another time.

See you then,
Bjorn';
insert into mail_templates (key, lang, subject, body) values ('accepted', 'nl', 'Je afspraak bij Bjorn’s Barber is bevestigd', 'Hoi {{name}},

Goed nieuws: je gevraagde tijd past. Je afspraak staat vast:

{{service}}
{{date}} om {{time}}
Ferdinandstraat 21, Axel

Tot dan,
Bjorn')
  on conflict (key, lang) do nothing;
update mail_templates set subject = 'Je afspraak bij Bjorn’s Barber is bevestigd', body = 'Hoi {{name}},

Goed nieuws: je gevraagde tijd past. Je afspraak staat vast:

{{service}}
{{date}} om {{time}}
Ferdinandstraat 21, Axel

Tot dan,
Bjorn'
  where key = 'accepted' and lang = 'nl' and subject = 'Je afspraak bij BarberBjorn is bevestigd' and body = 'Hoi {{name}},

Goed nieuws: je gevraagde tijd past. Je afspraak staat vast:

{{service}}
{{date}} om {{time}}
Ferdinandstraat 21, Axel

Tot dan,
Bjorn';
insert into mail_templates (key, lang, subject, body) values ('accepted', 'en', 'Your appointment at Bjorn’s Barber is confirmed', 'Hi {{name}},

Good news: the time you asked for works. Your appointment is set:

{{service}}
{{date}} at {{time}}
Ferdinandstraat 21, Axel

See you then,
Bjorn')
  on conflict (key, lang) do nothing;
update mail_templates set subject = 'Your appointment at Bjorn’s Barber is confirmed', body = 'Hi {{name}},

Good news: the time you asked for works. Your appointment is set:

{{service}}
{{date}} at {{time}}
Ferdinandstraat 21, Axel

See you then,
Bjorn'
  where key = 'accepted' and lang = 'en' and subject = 'Your appointment at BarberBjorn is confirmed' and body = 'Hi {{name}},

Good news: the time you asked for works. Your appointment is set:

{{service}}
{{date}} at {{time}}
Ferdinandstraat 21, Axel

See you then,
Bjorn';
insert into mail_templates (key, lang, subject, body) values ('declined', 'nl', 'Dat tijdstip lukt helaas niet', 'Hoi {{name}},

{{date}} om {{time}} lukt helaas niet. Kies een vrije tijd op de site, of stuur een mail terug, dan zoeken we samen een ander moment.

Groet,
Bjorn')
  on conflict (key, lang) do nothing;
update mail_templates set subject = 'Dat tijdstip lukt helaas niet', body = 'Hoi {{name}},

{{date}} om {{time}} lukt helaas niet. Kies een vrije tijd op de site, of stuur een mail terug, dan zoeken we samen een ander moment.

Groet,
Bjorn'
  where key = 'declined' and lang = 'nl' and subject = 'Dat tijdstip lukt helaas niet' and body = 'Hoi {{name}},

{{date}} om {{time}} lukt helaas niet. Kies een vrije tijd op de site, of stuur een mail terug, dan zoeken we samen een ander moment.

Groet,
Bjorn';
insert into mail_templates (key, lang, subject, body) values ('declined', 'en', 'That time doesn''t work, sorry', 'Hi {{name}},

{{date}} at {{time}} doesn''t work, sorry. Pick a free time on the site, or reply to this mail and we''ll find another moment together.

Best,
Bjorn')
  on conflict (key, lang) do nothing;
update mail_templates set subject = 'That time doesn''t work, sorry', body = 'Hi {{name}},

{{date}} at {{time}} doesn''t work, sorry. Pick a free time on the site, or reply to this mail and we''ll find another moment together.

Best,
Bjorn'
  where key = 'declined' and lang = 'en' and subject = 'That time doesn''t work, sorry' and body = 'Hi {{name}},

{{date}} at {{time}} doesn''t work, sorry. Pick a free time on the site, or reply to this mail and we''ll find another moment together.

Best,
Bjorn';
insert into mail_templates (key, lang, subject, body) values ('moved', 'nl', 'Je afspraak bij Bjorn’s Barber is verplaatst', 'Hoi {{name}},

Je afspraak is verplaatst naar een nieuw moment:

{{service}}
{{date}} om {{time}}
Ferdinandstraat 21, Axel

Past dit niet? Stuur even een mail terug, dan zoeken we een ander moment.

Tot dan,
Bjorn')
  on conflict (key, lang) do nothing;
update mail_templates set subject = 'Je afspraak bij Bjorn’s Barber is verplaatst', body = 'Hoi {{name}},

Je afspraak is verplaatst naar een nieuw moment:

{{service}}
{{date}} om {{time}}
Ferdinandstraat 21, Axel

Past dit niet? Stuur even een mail terug, dan zoeken we een ander moment.

Tot dan,
Bjorn'
  where key = 'moved' and lang = 'nl' and subject = 'Je afspraak bij BarberBjorn is verplaatst' and body = 'Hoi {{name}},

Je afspraak is verplaatst naar een nieuw moment:

{{service}}
{{date}} om {{time}}
Ferdinandstraat 21, Axel

Past dit niet? Stuur even een mail terug, dan zoeken we een ander moment.

Tot dan,
Bjorn';
insert into mail_templates (key, lang, subject, body) values ('moved', 'en', 'Your appointment at Bjorn’s Barber has moved', 'Hi {{name}},

Your appointment has moved to a new time:

{{service}}
{{date}} at {{time}}
Ferdinandstraat 21, Axel

Doesn''t this work for you? Just reply to this mail and we''ll find another time.

See you then,
Bjorn')
  on conflict (key, lang) do nothing;
update mail_templates set subject = 'Your appointment at Bjorn’s Barber has moved', body = 'Hi {{name}},

Your appointment has moved to a new time:

{{service}}
{{date}} at {{time}}
Ferdinandstraat 21, Axel

Doesn''t this work for you? Just reply to this mail and we''ll find another time.

See you then,
Bjorn'
  where key = 'moved' and lang = 'en' and subject = 'Your appointment at BarberBjorn has moved' and body = 'Hi {{name}},

Your appointment has moved to a new time:

{{service}}
{{date}} at {{time}}
Ferdinandstraat 21, Axel

Doesn''t this work for you? Just reply to this mail and we''ll find another time.

See you then,
Bjorn';
